// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/userprofile.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PhoneNumber_PhoneType int32

const (
	PhoneNumber_MOBILE PhoneNumber_PhoneType = 0
	PhoneNumber_HOME   PhoneNumber_PhoneType = 1
	PhoneNumber_WORK   PhoneNumber_PhoneType = 2
)

// Enum value maps for PhoneNumber_PhoneType.
var (
	PhoneNumber_PhoneType_name = map[int32]string{
		0: "MOBILE",
		1: "HOME",
		2: "WORK",
	}
	PhoneNumber_PhoneType_value = map[string]int32{
		"MOBILE": 0,
		"HOME":   1,
		"WORK":   2,
	}
)

func (x PhoneNumber_PhoneType) Enum() *PhoneNumber_PhoneType {
	p := new(PhoneNumber_PhoneType)
	*p = x
	return p
}

func (x PhoneNumber_PhoneType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PhoneNumber_PhoneType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_userprofile_proto_enumTypes[0].Descriptor()
}

func (PhoneNumber_PhoneType) Type() protoreflect.EnumType {
	return &file_proto_userprofile_proto_enumTypes[0]
}

func (x PhoneNumber_PhoneType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PhoneNumber_PhoneType.Descriptor instead.
func (PhoneNumber_PhoneType) EnumDescriptor() ([]byte, []int) {
	return file_proto_userprofile_proto_rawDescGZIP(), []int{2, 0}
}

type UserProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	FullName      string                 `protobuf:"bytes,4,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Bio           string                 `protobuf:"bytes,5,opt,name=bio,proto3" json:"bio,omitempty"`
	Interests     []string               `protobuf:"bytes,6,rep,name=interests,proto3" json:"interests,omitempty"`
	Address       *Address               `protobuf:"bytes,7,opt,name=address,proto3" json:"address,omitempty"`
	Phones        []*PhoneNumber         `protobuf:"bytes,8,rep,name=phones,proto3" json:"phones,omitempty"`
	IsActive      bool                   `protobuf:"varint,9,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserProfile) Reset() {
	*x = UserProfile{}
	mi := &file_proto_userprofile_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfile) ProtoMessage() {}

func (x *UserProfile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userprofile_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfile.ProtoReflect.Descriptor instead.
func (*UserProfile) Descriptor() ([]byte, []int) {
	return file_proto_userprofile_proto_rawDescGZIP(), []int{0}
}

func (x *UserProfile) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserProfile) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserProfile) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserProfile) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *UserProfile) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *UserProfile) GetInterests() []string {
	if x != nil {
		return x.Interests
	}
	return nil
}

func (x *UserProfile) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *UserProfile) GetPhones() []*PhoneNumber {
	if x != nil {
		return x.Phones
	}
	return nil
}

func (x *UserProfile) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *UserProfile) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *UserProfile) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Street        string                 `protobuf:"bytes,1,opt,name=street,proto3" json:"street,omitempty"`
	City          string                 `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	Country       string                 `protobuf:"bytes,4,opt,name=country,proto3" json:"country,omitempty"`
	PostalCode    string                 `protobuf:"bytes,5,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_proto_userprofile_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userprofile_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_proto_userprofile_proto_rawDescGZIP(), []int{1}
}

func (x *Address) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *Address) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Address) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Address) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Address) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

type PhoneNumber struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          PhoneNumber_PhoneType  `protobuf:"varint,1,opt,name=type,proto3,enum=userprofile.PhoneNumber_PhoneType" json:"type,omitempty"`
	Number        string                 `protobuf:"bytes,2,opt,name=number,proto3" json:"number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PhoneNumber) Reset() {
	*x = PhoneNumber{}
	mi := &file_proto_userprofile_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhoneNumber) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhoneNumber) ProtoMessage() {}

func (x *PhoneNumber) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userprofile_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhoneNumber.ProtoReflect.Descriptor instead.
func (*PhoneNumber) Descriptor() ([]byte, []int) {
	return file_proto_userprofile_proto_rawDescGZIP(), []int{2}
}

func (x *PhoneNumber) GetType() PhoneNumber_PhoneType {
	if x != nil {
		return x.Type
	}
	return PhoneNumber_MOBILE
}

func (x *PhoneNumber) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

type GetUserProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserProfileRequest) Reset() {
	*x = GetUserProfileRequest{}
	mi := &file_proto_userprofile_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProfileRequest) ProtoMessage() {}

func (x *GetUserProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userprofile_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProfileRequest.ProtoReflect.Descriptor instead.
func (*GetUserProfileRequest) Descriptor() ([]byte, []int) {
	return file_proto_userprofile_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserProfileRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetUserProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *UserProfile           `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserProfileResponse) Reset() {
	*x = GetUserProfileResponse{}
	mi := &file_proto_userprofile_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProfileResponse) ProtoMessage() {}

func (x *GetUserProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userprofile_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProfileResponse.ProtoReflect.Descriptor instead.
func (*GetUserProfileResponse) Descriptor() ([]byte, []int) {
	return file_proto_userprofile_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserProfileResponse) GetProfile() *UserProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type SaveUserProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *UserProfile           `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveUserProfileRequest) Reset() {
	*x = SaveUserProfileRequest{}
	mi := &file_proto_userprofile_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveUserProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveUserProfileRequest) ProtoMessage() {}

func (x *SaveUserProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userprofile_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveUserProfileRequest.ProtoReflect.Descriptor instead.
func (*SaveUserProfileRequest) Descriptor() ([]byte, []int) {
	return file_proto_userprofile_proto_rawDescGZIP(), []int{5}
}

func (x *SaveUserProfileRequest) GetProfile() *UserProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type SaveUserProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *UserProfile           `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveUserProfileResponse) Reset() {
	*x = SaveUserProfileResponse{}
	mi := &file_proto_userprofile_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveUserProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveUserProfileResponse) ProtoMessage() {}

func (x *SaveUserProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userprofile_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveUserProfileResponse.ProtoReflect.Descriptor instead.
func (*SaveUserProfileResponse) Descriptor() ([]byte, []int) {
	return file_proto_userprofile_proto_rawDescGZIP(), []int{6}
}

func (x *SaveUserProfileResponse) GetProfile() *UserProfile {
	if x != nil {
		return x.Profile
	}
	return nil
}

var File_proto_userprofile_proto protoreflect.FileDescriptor

const file_proto_userprofile_proto_rawDesc = "" +
	"\n" +
	"\x17proto/userprofile.proto\x12\vuserprofile\x1a\x1fgoogle/protobuf/timestamp.proto\"\x91\x03\n" +
	"\vUserProfile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1b\n" +
	"\tfull_name\x18\x04 \x01(\tR\bfullName\x12\x10\n" +
	"\x03bio\x18\x05 \x01(\tR\x03bio\x12\x1c\n" +
	"\tinterests\x18\x06 \x03(\tR\tinterests\x12.\n" +
	"\aaddress\x18\a \x01(\v2\x14.userprofile.AddressR\aaddress\x120\n" +
	"\x06phones\x18\b \x03(\v2\x18.userprofile.PhoneNumberR\x06phones\x12\x1b\n" +
	"\tis_active\x18\t \x01(\bR\bisActive\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x86\x01\n" +
	"\aAddress\x12\x16\n" +
	"\x06street\x18\x01 \x01(\tR\x06street\x12\x12\n" +
	"\x04city\x18\x02 \x01(\tR\x04city\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\x18\n" +
	"\acountry\x18\x04 \x01(\tR\acountry\x12\x1f\n" +
	"\vpostal_code\x18\x05 \x01(\tR\n" +
	"postalCode\"\x8a\x01\n" +
	"\vPhoneNumber\x126\n" +
	"\x04type\x18\x01 \x01(\x0e2\".userprofile.PhoneNumber.PhoneTypeR\x04type\x12\x16\n" +
	"\x06number\x18\x02 \x01(\tR\x06number\"+\n" +
	"\tPhoneType\x12\n" +
	"\n" +
	"\x06MOBILE\x10\x00\x12\b\n" +
	"\x04HOME\x10\x01\x12\b\n" +
	"\x04WORK\x10\x02\"'\n" +
	"\x15GetUserProfileRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"L\n" +
	"\x16GetUserProfileResponse\x122\n" +
	"\aprofile\x18\x01 \x01(\v2\x18.userprofile.UserProfileR\aprofile\"L\n" +
	"\x16SaveUserProfileRequest\x122\n" +
	"\aprofile\x18\x01 \x01(\v2\x18.userprofile.UserProfileR\aprofile\"M\n" +
	"\x17SaveUserProfileResponse\x122\n" +
	"\aprofile\x18\x01 \x01(\v2\x18.userprofile.UserProfileR\aprofile2\xcd\x01\n" +
	"\x12UserProfileService\x12Y\n" +
	"\x0eGetUserProfile\x12\".userprofile.GetUserProfileRequest\x1a#.userprofile.GetUserProfileResponse\x12\\\n" +
	"\x0fSaveUserProfile\x12#.userprofile.SaveUserProfileRequest\x1a$.userprofile.SaveUserProfileResponseBKZIgithub.com/sahilrana7582/go-grpc-graphql-microservice/userprofile/grpc/pbb\x06proto3"

var (
	file_proto_userprofile_proto_rawDescOnce sync.Once
	file_proto_userprofile_proto_rawDescData []byte
)

func file_proto_userprofile_proto_rawDescGZIP() []byte {
	file_proto_userprofile_proto_rawDescOnce.Do(func() {
		file_proto_userprofile_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_userprofile_proto_rawDesc), len(file_proto_userprofile_proto_rawDesc)))
	})
	return file_proto_userprofile_proto_rawDescData
}

var file_proto_userprofile_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_userprofile_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_userprofile_proto_goTypes = []any{
	(PhoneNumber_PhoneType)(0),      // 0: userprofile.PhoneNumber.PhoneType
	(*UserProfile)(nil),             // 1: userprofile.UserProfile
	(*Address)(nil),                 // 2: userprofile.Address
	(*PhoneNumber)(nil),             // 3: userprofile.PhoneNumber
	(*GetUserProfileRequest)(nil),   // 4: userprofile.GetUserProfileRequest
	(*GetUserProfileResponse)(nil),  // 5: userprofile.GetUserProfileResponse
	(*SaveUserProfileRequest)(nil),  // 6: userprofile.SaveUserProfileRequest
	(*SaveUserProfileResponse)(nil), // 7: userprofile.SaveUserProfileResponse
	(*timestamppb.Timestamp)(nil),   // 8: google.protobuf.Timestamp
}
var file_proto_userprofile_proto_depIdxs = []int32{
	2,  // 0: userprofile.UserProfile.address:type_name -> userprofile.Address
	3,  // 1: userprofile.UserProfile.phones:type_name -> userprofile.PhoneNumber
	8,  // 2: userprofile.UserProfile.created_at:type_name -> google.protobuf.Timestamp
	8,  // 3: userprofile.UserProfile.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 4: userprofile.PhoneNumber.type:type_name -> userprofile.PhoneNumber.PhoneType
	1,  // 5: userprofile.GetUserProfileResponse.profile:type_name -> userprofile.UserProfile
	1,  // 6: userprofile.SaveUserProfileRequest.profile:type_name -> userprofile.UserProfile
	1,  // 7: userprofile.SaveUserProfileResponse.profile:type_name -> userprofile.UserProfile
	4,  // 8: userprofile.UserProfileService.GetUserProfile:input_type -> userprofile.GetUserProfileRequest
	6,  // 9: userprofile.UserProfileService.SaveUserProfile:input_type -> userprofile.SaveUserProfileRequest
	5,  // 10: userprofile.UserProfileService.GetUserProfile:output_type -> userprofile.GetUserProfileResponse
	7,  // 11: userprofile.UserProfileService.SaveUserProfile:output_type -> userprofile.SaveUserProfileResponse
	10, // [10:12] is the sub-list for method output_type
	8,  // [8:10] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_userprofile_proto_init() }
func file_proto_userprofile_proto_init() {
	if File_proto_userprofile_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_userprofile_proto_rawDesc), len(file_proto_userprofile_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_userprofile_proto_goTypes,
		DependencyIndexes: file_proto_userprofile_proto_depIdxs,
		EnumInfos:         file_proto_userprofile_proto_enumTypes,
		MessageInfos:      file_proto_userprofile_proto_msgTypes,
	}.Build()
	File_proto_userprofile_proto = out.File
	file_proto_userprofile_proto_goTypes = nil
	file_proto_userprofile_proto_depIdxs = nil
}
